### ISSUE TITLE
Arrays and Nulls plural; other objects singular

### ISSUE THREAD

**Issue by alexekorn** [rossriley/php-scalar-objects#1]
Any reason for this?

If not, especially since this project is all about consistency, all should be either singular or plural (probably singular).

**Comment by rossriley** [comment]
Well spotted, yes, Array and Null are both protected keywords so can't be used as class names.

**Comment by alexekorn** [comment]
That totally makes sense.

I just realized how register_primitive_type_handler() from nikic's scalar_objects works, so given that you don't actually need to use those names directly, doesn't really matter.
