### ISSUE TITLE
Array should implement ArrayAccess

### ISSUE THREAD

**Issue by mnapoli** [rossriley/php-scalar-objects#10]
http://fr2.php.net/manual/en/class.arrayaccess.php

**Comment by rossriley** [comment]
Is there any value to doing this, the scalars already by definition support it since they are arrays.

Do we gain anything by being able to call the method? eg: 
    $array = [1,2,3,4,5,6];
    $array->offsetGet(0);  // 1

As opposed to just using
    $array[0];

**Comment by mnapoli** [comment]
You are right, I thought about this without taking into account that it's to be merge in php's core (not a userland library) :)
